# Site settings
title: NSF CSSI PI Meeting 2022
email: cxsong@purdue.edu
description: > # this means to ignore newlines until "baseurl:"
  NSF CSSI PI Meeting 2022
baseurl: "/2022-meeting"
#url: "https://cssi-pi-community.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - assets/fonts
    - assets/images
    - assets/js
    - assets/css

plugins:
  - jekyll-assets


theme: jekyll-theme-time-machine
