# Site settings
title: MGI PI Meeting 2024
email: elbert@jhu.edu
description: > # this means to ignore newlines until "baseurl:"
  NSF MGI PI Meeting 2024
baseurl: "/2024-meeting"
#url: "https://marda-alliance.github.io/MGI_PI_Meeting_2024/"

# Build settings
markdown: kramdown

assets:
  sources:
    - assets/fonts
    - assets/images
    - assets/js
    - assets/css

plugins:
  - jekyll-assets


theme: jekyll-theme-time-machine
